import type { NextPage } from 'next'
import Head from 'next/head'
import challenges from '../data.json'
import Grid from '../components/Grid'
import Header from '../components/Header'

const Home: NextPage = () => {
  return (
    <div>
      <Head>
        <title>Joseito Fernandes: Frontend Web Dev Challenges</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <Header />

      <main>
        <Grid challenges={challenges} />
      </main>
    </div>
  )
}

export default Home
