import type { NextPage } from 'next'
import Head from 'next/head'
import challenges from '../data.json'
import Grid from '../components/Grid'

const Home: NextPage = () => {

  return (
    <div>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main>
        <Grid challenges={challenges} />
      </main>
    </div>
  )
}

export default Home
